const randomNum = (min, max) =>
  Math.floor(Math.random() * (max - min + 1)) + min;

console.log(randomNum(5, 10));

function randomRange(myMin, myMax) {
  // Only change code below this line
  return Math.floor(Math.random() * (myMax + 1 - myMin) + myMin);
  // Only change code above this line
}

/*
The lowest random number that can be generated by randomRange should be equal to your minimum number, myMin.
Passed:The highest random number that can be generated by randomRange should be equal to your maximum number, myMax.
Passed:The random number generated by randomRange should be an integer, not a decimal.
Passed:randomRange should use both myMax and myMin, and return a random number in your range.*/
